### ISSUE TITLE
[gentoo-build] Image gentoo/stage3 not working for complex builds

### ISSUE THREAD

**Issue by vojeroen** [hartwork/binary-gentoo#13]
First of all: thanks for creating and sharing these tools. It was exactly what I was looking for!

I have been trying it out and it works like a charm for simple builds. However, I found that the gentoo/stage3 image is not good enough for more complex builds, e.g. based on the default/linux/amd64/17.1/desktop/plasma profile. It starts complaining about circular dependencies and slot conflicts. 

I needed a way to create a custom docker image, with more up to date packages and dependency conflicts already resolved, that could be used for these complex builds. I have made some modifications to your tools so that they could be used to generate this image as well.

I'll be submitting a pull request, if you're interested you can review it and see if you are open to merging it in your toolset.

This is the script I'm using to generate my base image, using the modifications in the pull request. It builds up the image in several steps, upgrading outdated packages in the process. The steps for freetype and harfbuzz are necessary to circumvent some dependencies as explained in this [forum topic](https://forums.gentoo.org/viewtopic-t-1138672-start-25-postdays-0-postorder-asc-highlight-.html?sid=2a0effa306874951c477f0603bced8a6).

In all `gentoo-build` commands, I'm then using the arg `--docker-image gentoo-build-host` to use this image for builds.

```
#!/usr/bin/env bash

# ~/portage-image/ is an empty directory, to keep a default config for the image build
# ~/portage/ contains the /etc/portage config of the consumer system

DOCKER_IMAGE="gentoo/stage3:amd64"
GENTOO_PROFILE="default/linux/amd64/17.1/desktop/plasma"
CFLAGS="<your CFLAGS>"
CXXFLAGS="${CFLAGS}"
LDFLAGS="<your LDFLAGS>"
CPU_FLAGS_X86="<your CPU_FLAGS_X86>"
MAKEOPTS="-j3 "

docker pull "${DOCKER_IMAGE}"

gentoo-image --docker-image "${DOCKER_IMAGE}" --gentoo-profile "default/linux/amd64/17.1" --makeopts "${MAKEOPTS}" --etc-portage ~/portage-image/ --distdir ~/distdir/ --portdir ~/portdir/ --pkgdir ~/pkgdir/ --logdir ~/logdir/ --cflags "${CFLAGS}" --cxxflags "${CXXFLAGS}" --ldflags "${LDFLAGS}" --cpu-flags-x86 "${CPU_FLAGS_X86}" --update @world                                                  

gentoo-image --docker-image "gentoo-build-host" --gentoo-profile "default/linux/amd64/17.1" --makeopts "${MAKEOPTS}" --etc-portage ~/portage-image/ --distdir ~/distdir/ --portdir ~/portdir/ --pkgdir ~/pkgdir/ --logdir ~/logdir/ --cflags "${CFLAGS}" --cxxflags "${CXXFLAGS}" --ldflags "${LDFLAGS}" --cpu-flags-x86 "${CPU_FLAGS_X86}" --use "-truetype -harfbuzz" media-libs/freetype                

gentoo-image --docker-image "gentoo-build-host" --gentoo-profile "default/linux/amd64/17.1" --makeopts "${MAKEOPTS}" --etc-portage ~/portage-image/ --distdir ~/distdir/ --portdir ~/portdir/ --pkgdir ~/pkgdir/ --logdir ~/logdir/ --cflags "${CFLAGS}" --cxxflags "${CXXFLAGS}" --ldflags "${LDFLAGS}" --cpu-flags-x86 "${CPU_FLAGS_X86}" --use "-truetype -harfbuzz" media-libs/harfbuzz                

gentoo-image --docker-image "gentoo-build-host" --gentoo-profile "default/linux/amd64/17.1" --makeopts "${MAKEOPTS}" --etc-portage ~/portage-image/ --distdir ~/distdir/ --portdir ~/portdir/ --pkgdir ~/pkgdir/ --logdir ~/logdir/ --cflags "${CFLAGS}" --cxxflags "${CXXFLAGS}" --ldflags "${LDFLAGS}" --cpu-flags-x86 "${CPU_FLAGS_X86}" --use "truetype harfbuzz" media-libs/freetype                  

gentoo-image --docker-image "gentoo-build-host" --gentoo-profile "${GENTOO_PROFILE}" --makeopts "${MAKEOPTS}" --etc-portage ~/portage/ --distdir ~/distdir/ --portdir ~/portdir/ --pkgdir ~/pkgdir/ --logdir ~/logdir/ --cflags "${CFLAGS}" --cxxflags "${CXXFLAGS}" --ldflags "${LDFLAGS}" --cpu-flags-x86 "${CPU_FLAGS_X86}" --update @world                                                             
```

**Comment by hartwork** [comment]
Hi @vojeroen,

I'm glad that the tool is useful to you, and I'd be curious to learn more about your scenario/use case/requirements on- or off-GitHub.  When I saw your star on the project the other day, I considered writing to you a la "hi, cool, please let me know if you get stuck".  I didn't do that eventually because getting mail after starring stuff on GitHub *can* feel weird, like being "stalked" or "watched", if you have never talked before…

I know about these circular dependencies issues — I had to work around them, too.  I wish you had contacted me before investing time in code on your end, because I might have saved you time.  My impression is that the problem solved by `gentoo-image` is already solved by a plain `Dockerfile`: the `Dockerfile` becomes the main "script" and you emerge things in there, until the cycles are out of the way, a bit like (smaller, same concept) https://hub.docker.com/r/hartwork/gentoo-stage3-plus-gentoolkit is doing. All the glue script needs to do then is call `docker build`, `tag`, `login`, `push`: all simple. With that mean at hand, is there still need for a new command `gentoo-image`?

Besides the `media-libs/freetype[harfbuzz]` cycle I also worked around:
- `dev-lang/python[bluetooth]` cycle
- `sys-libs/ncurses[gpm]` cycle
- `sys-fs/eudev[introspection]` cycle
- `sys-apps/dbus[X]` cycle
- …
- `virtual/libcrypt-2` update issues on `~amd64`
- Perl update subslot conflicts issues on `~amd64`

I'd rebuild and push my image to Ducker Hub every few days, but the `USE=bindist` topic is standing in my way right now.  I'd paste the `Dockerfile` here but it needs more cleanup, at least some.

What do you think?

Best, Sebastian

**Comment by vojeroen** [comment]
Hi Sebastian,

My use case is relatively straightforward: I have both a desktop system, running gentoo, and a server, running debian. Since the server is always on and mostly idling, I wanted to let it do the building and packaging for my desktop system. 

I always have the tendency to first try a bit and then discuss ;) . I have indeed thought a bit about using a Dockerfile to do this, similar to your example, but then I decided to try the `gentoo-image` solution for the following reasons:
* binary-gentoo already includes some nice features to set CFLAGS, mount directories etc, so no need to redo all that in a Dockerfile
* by using the build script from binary-gentoo, all packages that are built are immediately available as binary packages too. An in case of a rebuild, they can be pulled in instead of recompiling

Don't know if you noticed, but the PR also contains a new `--update` flag and some modifications to allow `@system` and `@world` as atoms, so this can be used now too to upgrade all packages in the stage3 image. That also gives less errors in builds afterwards.

**Comment by hartwork** [comment]
Hi @vojeroen, thanks for sharing your reasoning. Let me digest this some more.

**Comment by hartwork** [comment]
@vojeroen after thinking about things more, my impression is:
- the current pull request is good work on a technical level, brings some good new ideas, does a lot of things right
- commands `gentoo-image` and `gentoo-build` do "95% the same work" through user glasses
- reusing code in two CLI commands creates some tricky maintainability problems (e.g. if name `enforce_installation` changes in `build.py` nothing will detect that breakage with status quo); nothing impossible, but also not trivial (..)
- we'd probably be better of with extending command `gentoo-build` with the new docker image tagging (e.g. `--tag-docker-image IMAGE:TAG`) than with a new command `gentoo-image`
- if we do review ping-pong with my usual picky hat on, getting "from 80% to 100%" will likely take a bit of time on both your and my side, to be transparent with you

So before I post comments about details to the pull requests let's make sure we find a common ground for a way forward about two key things:
- are you okay if we trade `gentoo-image [..]` for `gentoo-build --tag-docker-image IMAGE:TAG [..]`, in general?
- are you okay with picky review and multiple rounds on the pull request? An alternative would be to swap seats: I take your ideas, create pull request(s), and you'd be in the review seat if you like.

What do you think?

**Comment by hartwork** [comment]
> * reusing code in two CLI commands creates some tricky maintainability problems (e.g. if name `enforce_installation` changes in `build.py` nothing will detect the breakage in `image.py` as is); nothing impossible, but also not trivial (..)

PS: @vojeroen I should probably update and elaborate on this^^ item:
- for the  `enforce_installation` going out-of-sync part, the fix is easy: extract a constant, use it everywhere, no more breakage
- what I had in mind for the remaining non-trivial technical aspect has turned out a non-issue by now (— [function `build`](https://github.com/hartwork/binary-gentoo/blob/12c30aa25a1ec4f1b62ebda228fe2b3a90266d95/binary_gentoo/internal/cli/build.py#L135) can still assume that config has all the shared argparse fields, _before_ and _after_ the PR)
- this whole topic and your interest in this software made it clear to me, that adding software tests can no longer be save here for some time later. After pull requests…

- #15
- #16
- #17
- #18 
- #19 
- #20 
- #21 
- #22

…the branch code coverage is at 49% now. I'll work on tests for command `gentoo-build`, next.

Best, Sebastian

**Comment by vojeroen** [comment]
@hartwork your observation that `gentoo-build` and `gentoo-image` are 95% identical, both from the user perspective as well as the code base, is definitely correct. Your proposal to replace `gentoo-image` by an additional attribute `--tag-docker-image` makes complete sense. 

I'll do the changes for that and add them to the PR, and then we can take it from there with the picky review :) . I have no problems with going back and forth, if you don't mind that it might take some time because I can't guarantee I'll be able to look at your comments or work on this every day.

**Comment by hartwork** [comment]
> @hartwork your observation that `gentoo-build` and `gentoo-image` are 95% identical, both from the user perspective as well as the code base, is definitely correct. Your proposal to replace `gentoo-image` by an additional attribute `--tag-docker-image` makes complete sense.

Cool!

> I'll do the changes for that and add them to the PR, and then we can take it from there with the picky review :) . I have no problems with going back and forth, if you don't mind that it might take some time because I can't guarantee I'll be able to look at your comments or work on this every day.

Okay cool, let's do that.

Also got your mail. I plan to do review and reply to your mail some time today.

**Comment by hartwork** [comment]
@vojeroen is this ticket ready to be closed as fixed? Anything missing?

**Comment by vojeroen** [comment]
Yes, this ticket is fixed now. Thanks :)
